version: '3'
services:
  backend:
    build: ./backend
    container_name: fastapi
    env_file:
      - .env
    restart: always
    volumes:
      - ./backend:/4ovisionannotator/backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    tty: true
    networks:
      - app-network
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}

  frontend:
    build: ./frontend
    container_name: react-frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/4ovisionannotator/frontend
      - /4ovisionannotator/frontend/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    tty: true
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

networks:
  app-network:
    driver: bridge
